/*
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package huawei.iap;

import com.huawei.hms.iap.IapClient;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;


@SuppressWarnings("ALL")
@Kroll.module(name="HuaweiIap", id="huawei.iap")
public class HuaweiIapModule extends KrollModule {
	public static final String TAG = "HuaweiIapModule";

	public static String API_KEY = "";

	@Kroll.constant public static final int PRICE_TYPE_CONSUMABLE = IapClient.PriceType.IN_APP_CONSUMABLE;
	@Kroll.constant public static final int PRICE_TYPE_NON_CONSUMABLE = IapClient.PriceType.IN_APP_NONCONSUMABLE;
	@Kroll.constant public static final int PRICE_TYPE_SUBSCRIPTION = IapClient.PriceType.IN_APP_SUBSCRIPTION;

	public HuaweiIapModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
	}

	@Kroll.getProperty
	public String getApiKey() {
		return API_KEY;
	}

	@Kroll.setProperty
	public void setApiKey(String value) {
		API_KEY = value;
	}

	@Kroll.method
	public void purchaseProduct() {

	}
}

